const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
const API="https://persepolis.ahoon201.workers.dev";
const PERS_MASTER="EQBxwHlh-mqsszryIRQeFpvaG91EqS3HWtiQo4h2-UzYlBAX";
const MAX_ENERGY=200;
const MILESTONES={1:[0,1],5:[317,46.31],12:[15000,125.60],25:[2869,133.14],50:[7730,151.48],100:[20812,193.57],200:[55920,288.33],300:[99611,391.35],400:[150000,500]};
let state=null,levels=[],connectedWallet="",tonUI=null,lastSync=0,tradeMode="buy";
function fmt(n,d=4){return Number(n||0).toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d})}
function me(){return tg?.initDataUnsafe?.user||{}}
function headers(){return {"Content-Type":"application/json","X-Telegram-Init-Data":tg?.initData||""}}
async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})},cache:"no-store"});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
function makeLevel(level){if(MILESTONES[level])return{level,hold:MILESTONES[level][0],speed:MILESTONES[level][1]};const ks=Object.keys(MILESTONES).map(Number).sort((a,b)=>a-b);for(let i=0;i<ks.length-1;i++){const a=ks[i],b=ks[i+1];if(level>a&&level<b){const t=(level-a)/(b-a);return{level,hold:Math.round(MILESTONES[a][0]+t*(MILESTONES[b][0]-MILESTONES[a][0])),speed:Number((MILESTONES[a][1]+t*(MILESTONES[b][1]-MILESTONES[a][1])).toFixed(2))}}return{level,hold:150000,speed:500}}
const fallback=Array.from({length:400},(_,i)=>makeLevel(i+1));
function cur(){return levels[(state?.level||1)-1]||fallback[(state?.level||1)-1]}
function next(){return levels[state?.level||1]||fallback[state?.level||1]}
function liveMined(){if(!state?.mining||!state?.lastMineAt)return Number(state?.mined||0);const s=Math.min(8*3600,Math.max(0,(Date.now()-state.lastMineAt)/1000));return Number(state.mined||0)+s*(cur()?.speed||1)/3600}
function set(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function render(){if(!state)return;const u=me(),c=cur(),n=next(),lm=liveMined(),wallet=Number(state.walletPers||0);set("homeName",(u.first_name||"Miner")+" ✓");set("homeLevel",state.level);set("homeStatus",state.mining?"MINING":"READY");set("homeNextHold",fmt(Math.max(0,(n?.hold||0)-wallet),0));set("saved",fmt(state.saved));set("mined",fmt(lm));set("homeRate",Number(c?.speed||1).toFixed(2));set("mineTimer",state.mining?new Date(Math.min(28800,Math.floor((Date.now()-state.lastMineAt)/1000))*1000).toISOString().slice(11,19):"00:00:00");set("walletPers",fmt(wallet));set("walletPers2",fmt(wallet));set("walletTotal",`${fmt(wallet)} PERS`);set("upgradeLevel",state.level);set("energy",`${Math.floor(state.energy??200)} / ${MAX_ENERGY}`);set("profileName",u.first_name||"Miner");set("profileId",u.id?`Telegram ID ${u.id}`:"Telegram");set("profileLevel",`LEVEL ${state.level}`);set("totalEarned",`${fmt(Number(state.saved||0)+lm)} PERS`);set("profileRef",`${fmt(state.referralEarned||0,0)} PERS`);set("invited",state.referrals||0);set("refEarned",fmt(state.referralEarned||0,0));set("refCount",`${state.referrals||0} ACTIVE`);const chip=document.getElementById("walletChip");if(chip)chip.textContent=connectedWallet?connectedWallet.slice(0,6)+"..."+connectedWallet.slice(-5):"CONNECT WALLET";set("walletTon",connectedWallet?connectedWallet.slice(0,6)+"..."+connectedWallet.slice(-5):"CONNECT WALLET");const link=document.getElementById("refLink");if(link)link.textContent=u.id?`https://t.me/Pirouzi6_bot?startapp=ref_${u.id}`:"Connect Telegram to create your invite link.";const mb=document.getElementById("mineBtn");if(mb)mb.textContent=state.mining?"STOP MINING":"START MINING";const ub=document.getElementById("upgradeBtn");if(ub)ub.textContent=n?`UPGRADE TO LEVEL ${n.level}`:"LEVEL 400 REACHED";renderMilestones();renderTasks()}
function renderMilestones(){const box=document.getElementById("levelMilestones");if(!box)return;box.innerHTML="";[1,5,12,25,50,100,200,300,400].forEach(l=>{const x=levels[l-1]||fallback[l-1];box.insertAdjacentHTML("beforeend",`<div class="milestone"><span>LEVEL ${l}</span><b>${fmt(x.hold,0)} PERS</b><span>${Number(x.speed).toFixed(2)} PERS/h</span></div>`)})}
function renderTasks(){const box=document.getElementById("taskList");if(!box)return;const tasks=[["daily","🎁","Check in daily",500],["telegram","✈️","Join Telegram",1000],["x","𝕏","Follow X",1000],["invite3","♙","Invite 3 friends",5000],["watch","▶","Watch video",1000],["swap","↔","Swap PERS",2000]];const done=state?.tasks||[];box.innerHTML=tasks.map(t=>{const key=t[0]==="daily"?`daily:${new Date().toISOString().slice(0,10)}`:t[0];const claimed=done.includes(key)||done.includes(t[0]);return`<div class="task"><div>${t[1]} ${t[2]}<small>+${t[3].toLocaleString()} PERS</small></div><button class="${claimed?"done":""}" data-task="${t[0]}">${claimed?"CLAIMED":"CLAIM"}</button></div>`}).join("");box.querySelectorAll("[data-task]").forEach(b=>b.onclick=()=>claimTask(b.dataset.task))}
async function claimTask(id){try{await api("/api/tasks/claim",{method:"POST",body:JSON.stringify({taskId:id})});await sync()}catch(e){alert(e.message)}}
async function sync(){try{const j=await api("/api/bootstrap",{method:"POST",body:JSON.stringify({ref:tg?.initDataUnsafe?.start_param||"",wallet:connectedWallet})});state=j.state;levels=j.levels?.length?j.levels:fallback;lastSync=Date.now();render()}catch(e){console.warn(e);if(!state){state={level:1,saved:0,mined:0,walletPers:0,energy:200,mining:false,lastMineAt:null,referrals:0,referralEarned:0,tasks:[]};levels=fallback;render()}}}
function show(name,btn){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.getElementById("screen-"+name)?.classList.add("active");document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n===btn));if(name==="leaderboard")loadLeaderboard()}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>show(b.dataset.screen,b));document.getElementById("leaderboardBtn")?.addEventListener("click",()=>show("leaderboard"));
document.getElementById("mineBtn").onclick=async()=>{try{await api(state.mining?"/api/mine/stop":"/api/mine/start",{method:"POST"});await sync()}catch(e){alert(e.message)}};
document.getElementById("claimBtn").onclick=async()=>{try{await api("/api/mine/claim",{method:"POST"});await sync()}catch(e){alert(e.message)}};
document.getElementById("upgradeBtn").onclick=async()=>{const n=next();if(!n)return;if(!connectedWallet){alert("Connect your TON wallet first.");return}try{await api("/api/level/upgrade",{method:"POST",body:JSON.stringify({level:n.level,wallet:connectedWallet})});await sync()}catch(e){alert(e.message)}};
document.getElementById("shareBtn").onclick=()=>{const id=me().id;if(!id){alert("Open this app from Telegram first.");return}const link=`https://t.me/Pirouzi6_bot?startapp=ref_${id}`;const url=`https://t.me/share/url?url=${encodeURIComponent(link)}&text=${encodeURIComponent("🏛️ Join PERSEPOLIS Mining")}`;tg?.openTelegramLink?tg.openTelegramLink(url):location.href=url};
function setTrade(mode){tradeMode=mode;document.getElementById("tradeBuy").classList.toggle("active",mode==="buy");document.getElementById("tradeSell").classList.toggle("active",mode==="sell");set("tradeTitle",mode==="buy"?"BUY PERS":"SELL PERS");document.getElementById("tradeAction").textContent=mode==="buy"?"BUY PERS":"SELL PERS";updateTrade()}
function updateTrade(){const v=Number(document.getElementById("payInput").value||0);document.getElementById("receiveInput").value=(tradeMode==="buy"?v*100000:v/100000).toLocaleString("en-US",{maximumFractionDigits:4})}
document.getElementById("tradeBuy").onclick=()=>setTrade("buy");document.getElementById("tradeSell").onclick=()=>setTrade("sell");document.getElementById("payInput").oninput=updateTrade;document.getElementById("buyBtn").onclick=()=>{show("wallet",document.querySelector('[data-screen="wallet"]'));setTrade("buy")};document.getElementById("sellBtn").onclick=()=>{show("wallet",document.querySelector('[data-screen="wallet"]'));setTrade("sell")};
document.getElementById("tradeAction").onclick=()=>alert("Swap is not executed until the verified PERS liquidity route is configured for this deployment.");
document.getElementById("sendBtn").onclick=()=>openWithdraw();document.getElementById("receiveBtn").onclick=()=>alert(connectedWallet?`TON wallet:\n${connectedWallet}`:"Connect a TON wallet first.");
function openWithdraw(){if(!connectedWallet){alert("Connect your TON wallet first.");return}set("withdrawAvailable",`${fmt(state.saved)} PERS`);document.getElementById("withdrawModal").style.display="flex"}document.getElementById("withdrawCancel").onclick=()=>document.getElementById("withdrawModal").style.display="none";document.getElementById("withdrawConfirm").onclick=async()=>{const amount=Number(document.getElementById("withdrawAmount").value||0);try{await api("/api/withdraw",{method:"POST",body:JSON.stringify({amount,wallet:connectedWallet})});document.getElementById("withdrawModal").style.display="none";alert("Withdrawal request submitted.");await sync()}catch(e){alert(e.message)}};
async function loadLeaderboard(){const box=document.getElementById("leaderboardList");box.innerHTML="<div class='task'>Loading…</div>";try{const j=await api("/api/leaderboard");box.innerHTML=(j.rows||[]).map((r,i)=>`<div class="leader-row"><span>#${i+1}</span><strong>${esc(r.first_name||r.username||"Miner")}</strong><span class="leader-level">LVL ${r.level||1}</span><b>${fmt(r.total,0)}</b></div>`).join("")||"<div class='task'>No data yet.</div>"}catch(e){box.innerHTML=`<div class='task'>${esc(e.message)}</div>`}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
async function initTon(){if(!window.TON_CONNECT_UI)return;try{tonUI=new TON_CONNECT_UI.TonConnectUI({manifestUrl:`${API}/tonconnect-manifest.json?v=11`,buttonRootId:"ton-connect"});tonUI.onStatusChange(async w=>{connectedWallet=w?.account?.address||"";if(connectedWallet){try{await api("/api/wallet/bind",{method:"POST",body:JSON.stringify({wallet:connectedWallet})})}catch(e){console.warn(e)}}await sync()})}catch(e){console.error(e)}}
setTrade("buy");sync();initTon();setInterval(render,1000);setInterval(()=>{if(Date.now()-lastSync>30000)sync()},10000);
