
CREATE TABLE IF NOT EXISTS users(
 id INTEGER PRIMARY KEY,
 username TEXT,
 level INTEGER NOT NULL DEFAULT 1,
 balance REAL NOT NULL DEFAULT 0,
 mined REAL NOT NULL DEFAULT 0,
 energy REAL NOT NULL DEFAULT 200,
 mining INTEGER NOT NULL DEFAULT 0,
 last_mine_at INTEGER NOT NULL DEFAULT 0,
 wallet TEXT,
 referrals INTEGER NOT NULL DEFAULT 0,
 referral_earned REAL NOT NULL DEFAULT 0,
 created_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS task_claims(
 user_id INTEGER NOT NULL,
 task_id TEXT NOT NULL,
 claimed_at INTEGER NOT NULL,
 PRIMARY KEY(user_id,task_id)
);
CREATE TABLE IF NOT EXISTS referrals(
 inviter_id INTEGER NOT NULL,
 invitee_id INTEGER NOT NULL UNIQUE,
 created_at INTEGER NOT NULL
);
