const REF_REWARD=5000;const LEVELS=Array.from({length:400},(_,i)=>({level:i+1,hold:i?Math.round(100+Math.pow(i/399,1.42)*149900):0,speed:i===11?125.6:i===399?500:+(1+i/399*499).toFixed(2)}));LEVELS[11]={level:12,hold:15000,speed:125.6};
function json(x,s=200){return new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*"}})}
async function sign(k,d){return crypto.subtle.sign("HMAC",k,new TextEncoder().encode(d))}async function hex(b){return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function telegram(init,token){let p=new URLSearchParams(init||""),hash=p.get("hash");if(!hash)throw Error("Missing Telegram initData");p.delete("hash");let data=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+"="+v).join("\n");let s=await crypto.subtle.importKey("raw",new TextEncoder().encode("WebAppData"),{name:"HMAC",hash:"SHA-256"},false,["sign"]),a=await sign(s,token),k=await crypto.subtle.importKey("raw",a,{name:"HMAC",hash:"SHA-256"},false,["sign"]);if(await hex(await sign(k,data))!==hash)throw Error("Invalid Telegram initData");return JSON.parse(p.get("user")||"{}")}
async function user(env,u){let x=await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(u.id).first();if(!x){let n=Math.floor(Date.now()/1000);await env.DB.prepare("INSERT INTO users(id,username,level,balance,mined,energy,mining,last_mine_at,created_at) VALUES(?,?,1,0,0,200,0,?,?)").bind(u.id,u.username||u.first_name||"",n,n).run();x=await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(u.id).first()}return x}
function accr(x){if(!x.mining)return[0,Math.floor(Date.now()/1000)];let n=Math.floor(Date.now()/1000),dt=Math.max(0,n-(x.last_mine_at||n)),l=LEVELS[x.level-1];return[Math.min(+x.energy,dt*l.speed/3600),n]}
async function settle(env,x){let[e,n]=accr(x);if(!e)return x;let mined=+x.mined+e,energy=Math.max(0,+x.energy-e);await env.DB.prepare("UPDATE users SET mined=?,energy=?,last_mine_at=? WHERE id=?").bind(mined,energy,n,x.id).run();return{...x,mined,energy,last_mine_at:n}}
function out(x){return{level:+x.level,balance:+x.balance,mined:+x.mined,energy:+x.energy,mining:!!x.mining,wallet:x.wallet||"",referrals:+(x.referrals||0),earned:+(x.referral_earned||0)}}
const valid=w=>/^[EU]Q[A-Za-z0-9_-]{46}$/.test(w);
export default{async fetch(req,env){let u=new URL(req.url);if(u.pathname==="/health")return json({ok:true,service:"PERSEPOLIS"});if(u.pathname==="/telegram/webhook"&&req.method==="POST"){try{let q=await req.json(),m=q.message;if(m?.text?.startsWith("/start"))await fetch("https://api.telegram.org/bot"+env.BOT_TOKEN+"/sendMessage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:m.chat.id,text:"🏛 PERSEPOLIS",reply_markup:{inline_keyboard:[[{text:"Open PERSEPOLIS",web_app:{url:env.WEBAPP_URL}}]]}})}catch(e){}return json({ok:true})}let tu;try{tu=await telegram(req.headers.get("X-Telegram-Init-Data"),env.BOT_TOKEN)}catch(e){return json({ok:false,error:e.message},401)}let x=await settle(env,await user(env,tu)),n=Math.floor(Date.now()/1000);if(u.pathname==="/api/bootstrap")return json({ok:true,state:out(x),levels:LEVELS});if(req.method!=="POST")return json({ok:false,error:"Method not allowed"},405);let b=await req.json().catch(()=>({}));
if(u.pathname==="/api/mine/start"){if(+x.energy<=0)return json({ok:false,error:"No energy"},400);await env.DB.prepare("UPDATE users SET mining=1,last_mine_at=? WHERE id=?").bind(n,tu.id).run();return json({ok:true,state:out({...x,mining:1,last_mine_at:n})})}
if(u.pathname==="/api/mine/stop"){await env.DB.prepare("UPDATE users SET mining=0,last_mine_at=? WHERE id=?").bind(n,tu.id).run();return json({ok:true,state:out({...x,mining:0,last_mine_at:n})})}
if(u.pathname==="/api/level/upgrade"){let z=LEVELS[+x.level];if(!z)return json({ok:false,error:"Maximum level"},400);if(+x.balance<z.hold)return json({ok:false,error:"Need "+z.hold+" PERS"},400);await env.DB.prepare("UPDATE users SET level=?,balance=balance-?,mining=0,last_mine_at=? WHERE id=?").bind(z.level,z.hold,n,tu.id).run();return json({ok:true,state:out({...x,level:z.level,balance:+x.balance-z.hold,mining:0,last_mine_at:n})})}
if(u.pathname==="/api/wallet/bind"){let w=String(b.wallet||"").trim();if(!valid(w))return json({ok:false,error:"Invalid TON wallet address"},400);await env.DB.prepare("UPDATE users SET wallet=? WHERE id=?").bind(w,tu.id).run();return json({ok:true,state:out({...x,wallet:w})})}
if(u.pathname==="/api/tasks/claim"&&b.taskId==="daily"){let k=new Date().toISOString().slice(0,10);try{await env.DB.prepare("INSERT INTO task_claims(user_id,task_id,claim_key,claimed_at) VALUES(?,?,?,?)").bind(tu.id,"daily",k,n).run()}catch(e){return json({ok:false,error:"Already claimed today"},400)}await env.DB.prepare("UPDATE users SET balance=balance+500 WHERE id=?").bind(tu.id).run();return json({ok:true,state:out({...x,balance:+x.balance+500})})}return json({ok:false,error:"Not found"},404)}};